language: node_js

node_js:
  - "11"
  - "10"
  - "9"
  - "8"

os:
  - linux
  - osx
  - windows
    
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'  